twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        github_user: '%github_user%'
        author: '%author%'
        website_url: '%website_url%'
        ga: '%ga%'
        analytic_website_id: '%analytic_website_id%'
when@test:
    twig:
        strict_variables: true
